use delivery-test;

CREATE TABLE `client` (
	id INT PRIMARY KEY AUTO_INCREMENT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL,
	name VARCHAR(25) NOT NULL,
	doc VARCHAR(14) NOT NULL
	dt_nasc TIMESTAMP NOT NULL,
	email VARCHAR(100) NULL  DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE `address` (
	id INT PRIMARY KEY AUTO_INCREMENT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL,
	lograudoro VARCHAR(255) NOT NULL
	numero VARCHAR(10) NOT NULL,
	cep VARCHAR(7) NOT NULL,
	cidade VARCHAR(255) NOT NULL,
	complemento VARCHAR(127) NULL,
	bairro VARCHAR(127) NULL,
	id_cliente INT,
	FOREIGN KEY (id_cliente) REFERENCES cliente(id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;